version: '3'
services:

  ubuntu-core:
    build: .
    ports:
      - "8060:60"
    environment:
    - ".env"

  go:
    build: "./context/go"
    ports:
      - "5000:5000"
      - "8080:80"
    volumes: ["/Users/tim/go/src:/go/src"]
   # environment:
      #"./context/go/.env"

  redis:
    image: redis